---
resources:
- name: resource-tutorialgit
  type: git
  source:
    uri: https://github.com/dwan4351/concourse-tutorial.git
    branch: develop
    git_config:
      - name: safe.directory
        value: '*'

- name: resource-app
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git
    git_config:
      - name: safe.directory
        value: '*'

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
  - get: resource-app
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.yml
